jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure environment variables
        run: |
          export TF_VAR_my_secret="${{ secrets.GITHUBTOKEN }}"
      - name: Terraform apply
        run: |
          terraform init
          terraform apply -auto-approve
